version: '3'
services:

  nginx:
    image: nginx
    ports:
      - "5000:80"
    volumes:
      - .:/app
      - ./.site-conf:/etc/nginx/conf.d/default.conf

  app:
    build:
      context: ./
    volumes:
      - .:/app

  db:
    image: mariadb
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: example
      MYSQL_DATABASE: app_db
    ports:
      - "3000:3306"
